---
- hosts: 
  become: yes
  tasks:
   - name: Add relay line
     lineinfile: 
        path: /etc/postfix/main.cf
        regexp: '^#relayhost'
        line: 'relayhost = emailserver.com 
        state: present
      
